# Generated by Django 4.2.7 on 2023-11-27 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_parent_chatreply_chat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatreply',
            name='chat',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_reply',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.chatreply'),
            preserve_default=False,
        ),
    ]
