# Generated by Django 4.2.7 on 2023-11-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='account/%Y/%m/%d/', verbose_name='프로필 사진'),
        ),
    ]
